- name: Create user for prometheus
  shell: useradd --no-create-home prometheus

- name: Create library and config folders
  command: |
    mkdir /etc/prometheus
    mkdir /var/lib/prometheus

- name: Get the latest Prometheus binaries
  shell: wget https://github.com/prometheus/prometheus/releases/download/v2.41.0/prometheus-2.41.0.linux-amd64.tar.gz

- name: Extract the tarball
  command: tar xvfz prometheus-2.41.0.linux-amd64.tar.gz

- name: "move prometheus binary to /usr/local/bin"
  copy:
    src: prometheus-2.41.0.linux-amd64/prometheus
    dest: /usr/local/bin/prometheus
    remote_src: yes
    mode: "0777

- name: "move prometheus binary to /usr/local/bin"
  copy:
    src: prometheus-2.41.0.linux-amd64/prometheus
    dest: /usr/local/bin/prometheus
    remote_src: yes
    mode: "0777i
