---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "django-service"
  namespace: "default"
  labels:
    app: "django"
spec:
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 80
  selector:
    app: "django"
  type: "LoadBalancer"
  loadBalancerIP: "54.160.143.164"
