---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "django-service"
  namespace: "default"
  labels:
    app: "django"
spec:
  ports:
  - protocol: "TCP"
    port: "0.0.0.0:8000"
    targetPort: 80
  selector:
    app: "django"
  type: "LoadBalancer"
  loadBalancerIP: "44.197.200.90"
