# Postgres config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

# Postgres storage volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# Postgres deployment
apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: postgres-deployment 
spec:
  selector:
    matchLabels:
      app: postgres 
      tier: backend 
      track: stable 
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: postgres 
        tier: backend 
        track: stable 
    spec:
      containers:
      - image: postgres:13 # use your own image here if you have one 
        name: postgres 
        envFrom:
        - configMapRef:
            name: postgres-config  
        ports:
        - containerPort: 5432 
          name :postgres-port  
        volumeMounts :
        - mountPath : /postgres:13 # change this according to your image  
          name :postgres-storage 

      volumes :
      - name :postgres-storage  
        persistentVolumeClaim :
          claimName :postgres-pv-claim 

# Postgres service 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-container
    tier: backend
  name: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: postgres
  sessionAffinity: None
  type: ClusterIP