version: "3.9"

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  app:
    environment:
      APP_URL: "https://8000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/django

networks:
  internal-network:
    driver: bridge
    name: django-framwork

volumes:
  db:
    driver: local

